name: Test

on: 
  pull_request:
    branches:    
      - main
    types: [opened, reopened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5.0.0
      - name: Install dependencies
        run: |
          ls
          echo "Operating system is ${{ runner.os }}"
        if: runner.os == 'Linux' || runner.os == 'macOS'
      - name: Build
        run: go build -v ./...
      - name: Test with the Go CLI
        run: go test
            
